### ISSUE TITLE
Use larger images within the content syndicate plug in

### ISSUE THREAD

**Issue by slocker3** [washingtonstateuniversity/research.wsu.edu#5]
Currently the "excerpts" for the content syndicate pulls in the thumbnail, this is logical, but we would like for it to bring in a larger, uncropped version of the associated feature image.

**Comment by jeremyfelt** [comment]
- We want to pull in the "Featured Image" assigned to a post, not the "Thumbnail" or "Background Image", correct?
- Are these all from news.wsu.edu or other sources as well?
- Is there a max resolution for the image that we'll be using once it's in research?

**Comment by slocker3** [comment]
- featured image is correct
- these are currently from research.wsu.edu, but is very likely to pull from news.wsu.edu once that site has been updated.
- It appears that most of the featured images are uploaded with a width of 600px. I think that should be our max for within the syndicate on research at this time.

**Comment by jeremyfelt** [comment]
:+1:

I'm going to look for the generated `spine-medium_size` image (792px width) if it exists as that will allow for larger images to be uploaded in the future. If that isn't available, we can fallback to the original image and assume that it's less than 792px wide.

**Comment by slocker3** [comment]
Perfect

**Comment by jeremyfelt** [comment]
This relies on https://github.com/washingtonstateuniversity/WSUWP-Content-Syndicate/issues/36 so that we can adjust things solely for research.wsu.edu
